RebootIT.TimesheetApp/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RebootIT.TimesheetApp.Data;

namespace RebootIT.TimesheetApp.Controllers
{
    public class ClientsController : Controller
    {
        private readonly TimesheetDbContext _context;

        public ClientsController(TimesheetDbContext context)
        {
            _context = context;
        }

        // GET: Clients
        public async Task<IActionResult> Index()
        {
            return View(await _context.Clients.ToListAsync());
        }

        // GET: Clients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .FirstOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // GET: Clients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CompanyName,BillingAddress,ContactName,ContactTelephone,ContactEmail")] Client client)
        {
            if (ModelState.IsValid)
            {
                _context.Add(client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CompanyName,BillingAddress,ContactName,ContactTelephone,ContactEmail")] Client client)
        {
            if (id != client.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .FirstOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var client = await _context.Clients.FindAsync(id);
            _context.Clients.Remove(client);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientExists(int id)
        {
            return _context.Clients.Any(e => e.Id == id);
        }
    }
}

RebootIT.TimesheetApp/Controllers/TimesheetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RebootIT.TimesheetApp.Data;

namespace RebootIT.TimesheetApp.Controllers
{
    public class TimesheetsController : Controller
    {
        private readonly TimesheetDbContext _context;

        public TimesheetsController(TimesheetDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int? staffId, int? clientId, int? locationId)
        {
            IQueryable<Timesheet> timesheet = timesheet = _context.Timesheets
                                        .Include(t => t.Client)
                                        .Include(t => t.Location)
                                        .Include(t => t.Staff)
                                        ;

            if (staffId != null)
            {
                timesheet = timesheet.Where(t => t.StaffId == staffId);
                ViewData["staffId"] = staffId;
            }
            else if (clientId != null)
            {
                timesheet =  timesheet.Where(t => t.ClientId == clientId);
                ViewData["clientId"] = clientId;
            }
            else if (locationId != null)
            {
                timesheet = timesheet.Where(t => t.LocationId == locationId);
                ViewData["locationId"] = locationId;
            }

            if (timesheet == null)
            {
                return NotFound();
            }

            return View(await timesheet.ToListAsync());
        }

        // GET: Timesheets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
           
            var timesheet = await _context.Timesheets
                .Include(t => t.Client)
                .Include(t => t.Location)
                .Include(t => t.Staff)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (timesheet == null)
            {
                return NotFound();
            }
            return View(timesheet);
        }

        // GET: Timesheets/Create
        public IActionResult Create(int? staffId, int? clientId, int? locationId)
        {
            ViewData["StaffId"] = new SelectList(_context.Staff, "Id", "FullName");
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "CompanyName");
            ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "Name");

            if (staffId != null)
            {
                ViewData["StaffId"] = new SelectList(_context.Staff, "Id", "FullName", staffId);
            }

            if (clientId != null)
            {
                ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "CompanyName", clientId);
            }

            if(locationId != null)
            {
                ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "Name", locationId);
            }
            
            
            return View();
        }

        // POST: Timesheets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MinutesWorked,StaffId,ClientId,LocationId")] Timesheet timesheet)
        {
            if (ModelState.IsValid)
            {
                _context.Add(timesheet);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            } 

            return View(timesheet);
        }

        // GET: Timesheets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timesheet = await _context.Timesheets.FindAsync(id);
            if (timesheet == null)
            {
                return NotFound();
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "CompanyName", timesheet.ClientId);
            ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "Name", timesheet.LocationId);
            ViewData["StaffId"] = new SelectList(_context.Staff, "Id", "Email", timesheet.StaffId);
            return View(timesheet);
        }

        // POST: Timesheets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MinutesWorked,StaffId,ClientId,LocationId")] Timesheet timesheet)
        {
            if (id != timesheet.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(timesheet);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TimesheetExists(timesheet.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "BillingAddress", timesheet.ClientId);
            ViewData["LocationId"] = new SelectList(_context.Locations, "Id", "Address", timesheet.LocationId);
            ViewData["StaffId"] = new SelectList(_context.Staff, "Id", "Email", timesheet.StaffId);
            return View(timesheet);
        }

        // GET: Timesheets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timesheet = await _context.Timesheets
                .Include(t => t.Client)
                .Include(t => t.Location)
                .Include(t => t.Staff)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (timesheet == null)
            {
                return NotFound();
            }
            ViewData["StaffId"] = new SelectList(_context.Staff, "Id", "Email");
            return View(timesheet);
        }

        // POST: Timesheets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var timesheet = await _context.Timesheets.FindAsync(id);
            _context.Timesheets.Remove(timesheet);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TimesheetExists(int id)
        {
            return _context.Timesheets.Any(e => e.Id == id);
        }
    }
}

RebootIT.TimesheetApp/Views/Clients/Create.cshtml
@model RebootIT.TimesheetApp.Data.Client

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Client</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CompanyName" class="control-label"></label>
                <input asp-for="CompanyName" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingAddress" class="control-label"></label>
                <input asp-for="BillingAddress" class="form-control" />
                <span asp-validation-for="BillingAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactName" class="control-label"></label>
                <input asp-for="ContactName" class="form-control" />
                <span asp-validation-for="ContactName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactTelephone" class="control-label"></label>
                <input asp-for="ContactTelephone" class="form-control" />
                <span asp-validation-for="ContactTelephone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactEmail" class="control-label"></label>
                <input asp-for="ContactEmail" class="form-control" />
                <span asp-validation-for="ContactEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RebootIT.TimesheetApp/Views/Clients/Delete.cshtml
@model RebootIT.TimesheetApp.Data.Client

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Client</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BillingAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BillingAddress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ContactName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ContactName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ContactTelephone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ContactTelephone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ContactEmail)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ContactEmail)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RebootIT.TimesheetApp/Views/Clients/Details.cshtml
@model RebootIT.TimesheetApp.Data.Client

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Client</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CompanyName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CompanyName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BillingAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BillingAddress)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ContactName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ContactName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ContactTelephone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ContactTelephone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ContactEmail)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ContactEmail)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RebootIT.TimesheetApp/Views/Clients/Edit.cshtml
@model RebootIT.TimesheetApp.Data.Client

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Client</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CompanyName" class="control-label"></label>
                <input asp-for="CompanyName" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BillingAddress" class="control-label"></label>
                <input asp-for="BillingAddress" class="form-control" />
                <span asp-validation-for="BillingAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactName" class="control-label"></label>
                <input asp-for="ContactName" class="form-control" />
                <span asp-validation-for="ContactName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactTelephone" class="control-label"></label>
                <input asp-for="ContactTelephone" class="form-control" />
                <span asp-validation-for="ContactTelephone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactEmail" class="control-label"></label>
                <input asp-for="ContactEmail" class="form-control" />
                <span asp-validation-for="ContactEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RebootIT.TimesheetApp/Views/Clients/Index.cshtml
@model IEnumerable<RebootIT.TimesheetApp.Data.Client>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BillingAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactTelephone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactEmail)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BillingAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactTelephone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactEmail)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
                <a asp-controller="Timesheets" asp-action="Index" asp-route-clientid="@item.Id">Timesheet</a>
            </td>
        </tr>
}
    </tbody>
</table>